// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {management} from '../models';

export function DeleteCluster(arg1:string):Promise<Error>;

export function GetClusters():Promise<Array<management.ClusterHeader>>;

export function GetNodesStatus(arg1:string):Promise<Array<management.NodeStatus>>;
