// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {management} from '../models';

export function GetNodesStatus():Promise<Array<management.NodeStatus>>;
