// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHelmChart(arg1, arg2) {
  return window['go']['management']['Service']['AddHelmChart'](arg1, arg2);
}

export function AddK8sResource(arg1, arg2) {
  return window['go']['management']['Service']['AddK8sResource'](arg1, arg2);
}

export function DeleteCluster(arg1) {
  return window['go']['management']['Service']['DeleteCluster'](arg1);
}

export function DeleteHelmChart(arg1, arg2) {
  return window['go']['management']['Service']['DeleteHelmChart'](arg1, arg2);
}

export function DeleteK8sResource(arg1, arg2) {
  return window['go']['management']['Service']['DeleteK8sResource'](arg1, arg2);
}

export function GetClusters() {
  return window['go']['management']['Service']['GetClusters']();
}

export function GetHelpAppsStatus(arg1) {
  return window['go']['management']['Service']['GetHelpAppsStatus'](arg1);
}

export function GetNodesStatus(arg1) {
  return window['go']['management']['Service']['GetNodesStatus'](arg1);
}

export function InstallHelmChart(arg1, arg2) {
  return window['go']['management']['Service']['InstallHelmChart'](arg1, arg2);
}

export function InstallK8sResource(arg1, arg2) {
  return window['go']['management']['Service']['InstallK8sResource'](arg1, arg2);
}

export function UninstallHelmChart(arg1, arg2) {
  return window['go']['management']['Service']['UninstallHelmChart'](arg1, arg2);
}

export function UninstallK8sResource(arg1, arg2) {
  return window['go']['management']['Service']['UninstallK8sResource'](arg1, arg2);
}

export function UpdateHelmChartData(arg1, arg2) {
  return window['go']['management']['Service']['UpdateHelmChartData'](arg1, arg2);
}

export function UpdateK8sResourcesData(arg1, arg2) {
  return window['go']['management']['Service']['UpdateK8sResourcesData'](arg1, arg2);
}
