// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCluster(arg1) {
  return window['go']['management']['Service']['DeleteCluster'](arg1);
}

export function GetClusters() {
  return window['go']['management']['Service']['GetClusters']();
}

export function GetNodesStatus(arg1) {
  return window['go']['management']['Service']['GetNodesStatus'](arg1);
}
