// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k4p} from '../models';
import {management} from '../models';

export function AddHelmChart(arg1:string,arg2:k4p.HelmApp):Promise<string>;

export function AddK8sResource(arg1:string,arg2:k4p.K8sResource):Promise<string>;

export function DeleteCluster(arg1:string):Promise<Error>;

export function DeleteHelmChart(arg1:string,arg2:string):Promise<Error>;

export function DeleteK8sResource(arg1:string,arg2:string):Promise<Error>;

export function GetClusters():Promise<Array<management.ClusterHeader>>;

export function GetHelpAppsStatus(arg1:string):Promise<Array<management.HelmAppStatus>>;

export function GetNodesStatus(arg1:string):Promise<Array<management.NodeStatus>>;

export function InstallHelmChart(arg1:string,arg2:string):Promise<Error>;

export function InstallK8sResource(arg1:string,arg2:string):Promise<Error>;

export function UninstallHelmChart(arg1:string,arg2:string):Promise<Error>;

export function UninstallK8sResource(arg1:string,arg2:string):Promise<Error>;

export function UpdateHelmChartData(arg1:string,arg2:k4p.HelmApp):Promise<Error>;

export function UpdateK8sResourcesData(arg1:string,arg2:k4p.K8sResource):Promise<Error>;
