// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k4p} from '../models';

export function GenerateDefaultCluster():Promise<k4p.Cluster>;
