// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCluster(arg1) {
  return window['go']['provisioner']['Service']['CreateCluster'](arg1);
}

export function GetNetworkBridges() {
  return window['go']['provisioner']['Service']['GetNetworkBridges']();
}

export function GetStorage() {
  return window['go']['provisioner']['Service']['GetStorage']();
}

export function SetupEnvironmentOnProxmox() {
  return window['go']['provisioner']['Service']['SetupEnvironmentOnProxmox']();
}
