// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k4p} from '../models';

export function CreateCluster(arg1:k4p.ProvisionRequest):Promise<void>;

export function GetNetworkBridges():Promise<Array<string>>;

export function GetStorage():Promise<Array<string>>;

export function SetupEnvironmentOnProxmox():Promise<void>;
