// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncodeUsingBCrypt(arg1) {
  return window['go']['auth']['Service']['EncodeUsingBCrypt'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['auth']['Service']['Login'](arg1, arg2, arg3);
}
