// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncodeUsingBCrypt(arg1:string):Promise<string>;

export function GetProxmoxIp():Promise<string>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Logout():Promise<void>;
