// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncodeUsingBCrypt(arg1) {
  return window['go']['service']['PasswordEncoder']['EncodeUsingBCrypt'](arg1);
}
