// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';

export function LoadProject():Promise<service.ProjectData>;

export function OpenProjectDialog():Promise<boolean>;

export function SaveKubeConfigDialog():Promise<Error>;

export function SaveProject(arg1:service.ProjectData):Promise<Error>;

export function SaveProjectDialog():Promise<boolean>;

export function SaveSshAuthorizationKeyDialog():Promise<Error>;

export function SaveSshPrivateKeyDialog():Promise<Error>;

export function SetContext(arg1:context.Context):void;
