// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxmox} from '../models';
import {service} from '../models';
import {context} from '../models';

export function GetDefaultNetwork():Promise<proxmox.Network|Error>;

export function GetDefaultVmId():Promise<number|Error>;

export function GetFirstAddressFromFreePool():Promise<string>;

export function LoadProject():Promise<service.ProjectData|Error>;

export function SaveKubeConfigDialog():Promise<Error>;

export function SaveProjectDialog():Promise<boolean|Error>;

export function SaveSshPrivateKeyDialog():Promise<Error>;

export function SetContext(arg1:context.Context):void;

export function GetDefaultStorage():Promise<string|Error>;

export function OpenProjectDialog():Promise<boolean|Error>;

export function SaveProject(arg1:service.ProjectData):Promise<Error>;

export function SaveSshAuthorizationKeyDialog():Promise<Error>;
