// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadProject() {
  return window['go']['service']['ProjectService']['LoadProject']();
}

export function OpenProjectDialog() {
  return window['go']['service']['ProjectService']['OpenProjectDialog']();
}

export function SaveKubeConfigDialog() {
  return window['go']['service']['ProjectService']['SaveKubeConfigDialog']();
}

export function SaveProject(arg1) {
  return window['go']['service']['ProjectService']['SaveProject'](arg1);
}

export function SaveProjectDialog() {
  return window['go']['service']['ProjectService']['SaveProjectDialog']();
}

export function SaveSshAuthorizationKeyDialog() {
  return window['go']['service']['ProjectService']['SaveSshAuthorizationKeyDialog']();
}

export function SaveSshPrivateKeyDialog() {
  return window['go']['service']['ProjectService']['SaveSshPrivateKeyDialog']();
}

export function SetContext(arg1) {
  return window['go']['service']['ProjectService']['SetContext'](arg1);
}
