// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCluster(arg1) {
  return window['go']['service']['ProvisionerService']['CreateCluster'](arg1);
}

export function GetNetworkBridges() {
  return window['go']['service']['ProvisionerService']['GetNetworkBridges']();
}

export function GetStorage() {
  return window['go']['service']['ProvisionerService']['GetStorage']();
}

export function SetupEnvironmentOnProxmox() {
  return window['go']['service']['ProvisionerService']['SetupEnvironmentOnProxmox']();
}
