// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {k4p} from '../models';

export function GetNetworkBridges():Promise<Array<string>|Error>;

export function GetStorage():Promise<Array<string>|Error>;

export function SetupEnvironmentOnProxmox():Promise<Error>;

export function CreateCluster(arg1:k4p.ProvisionRequest):Promise<Error>;
