// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tasklog} from '../models';

export function ClearTaskLog():Promise<number>;

export function GetTaskLog():Promise<Array<tasklog.Task>>;
