// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAndSetupApp() {
  return window['go']['database']['Service']['AcceptAndSetupApp']();
}

export function IsFirstRunOfApp() {
  return window['go']['database']['Service']['IsFirstRunOfApp']();
}

export function LoadCluster(arg1) {
  return window['go']['database']['Service']['LoadCluster'](arg1);
}

export function LoadDatabase() {
  return window['go']['database']['Service']['LoadDatabase']();
}

export function SaveDatabase(arg1) {
  return window['go']['database']['Service']['SaveDatabase'](arg1);
}

export function SaveKubeConfigDialog(arg1) {
  return window['go']['database']['Service']['SaveKubeConfigDialog'](arg1);
}

export function SaveSshAuthorizationKeyDialog(arg1) {
  return window['go']['database']['Service']['SaveSshAuthorizationKeyDialog'](arg1);
}

export function SaveSshPrivateKeyDialog(arg1) {
  return window['go']['database']['Service']['SaveSshPrivateKeyDialog'](arg1);
}

export function SetContext(arg1) {
  return window['go']['database']['Service']['SetContext'](arg1);
}
