// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function LogFileLocation() {
  return window['go']['app']['App']['LogFileLocation']();
}
