// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadProject() {
  return window['go']['project']['Service']['LoadProject']();
}

export function OpenProjectDialog() {
  return window['go']['project']['Service']['OpenProjectDialog']();
}

export function SaveKubeConfigDialog() {
  return window['go']['project']['Service']['SaveKubeConfigDialog']();
}

export function SaveProject(arg1) {
  return window['go']['project']['Service']['SaveProject'](arg1);
}

export function SaveProjectDialog() {
  return window['go']['project']['Service']['SaveProjectDialog']();
}

export function SaveSshAuthorizationKeyDialog() {
  return window['go']['project']['Service']['SaveSshAuthorizationKeyDialog']();
}

export function SaveSshPrivateKeyDialog() {
  return window['go']['project']['Service']['SaveSshPrivateKeyDialog']();
}

export function SetContext(arg1) {
  return window['go']['project']['Service']['SetContext'](arg1);
}
