// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTaskLog() {
  return window['go']['tasklog']['Service']['ClearTaskLog']();
}

export function GetTaskLog() {
  return window['go']['tasklog']['Service']['GetTaskLog']();
}
